# analysis_options.yaml
# Koozen Admin — Strict analyzer configuration (no external includes)
# Enforces high-signal lints suitable for Flutter + Hexagonal Architecture.
# TODO: KOZ-1 — Migrate to `include: package:flutter_lints/flutter.yaml` after pubspec is added.

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # Core reliability
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - cancel_subscriptions
    - close_sinks
    - no_adjacent_strings_in_list
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - tighten_type_of_initializing_formals
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_nullable_for_final_variable_declarations
    - use_full_hex_values_for_flutter_colors

    # API clarity
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_renaming_method_parameters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - eol_at_end_of_file
    - lines_longer_than_80_chars # Prefer readability; can be relaxed per file with // ignore.
    - prefer_expression_function_bodies
    - sort_constructors_first
    - sort_pub_dependencies

    # Null-safety & typing
    - avoid_type_to_string
    - cast_nullable_to_non_nullable
    - null_check_on_nullable_type_parameter
    - unnecessary_null_checks

    # Flutter-specific guidance
    - avoid_unnecessary_containers
    - prefer_const_constructors_in_immutables
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

# Per-directory overrides (future-proofing for test utils or generated code)
# analyzer:
#   exclude:
#     - "lib/**/generated/**"
