name: koozen_admin
description: >
  Koozen Admin — Dropshipping Management System.
  A Flutter-based administrative app with Arabic/English support,
  built using Hexagonal Architecture for scalability and maintainability.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Data handling
  equatable: ^2.0.5

  # HTTP & APIs
  http: ^1.2.1

  # Dependency injection
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Mocking & testing utilities
  mocktail: ^1.0.3

  # Code generation (for DTOs/entities if needed later)
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
